### ISSUE TITLE
Switch invisible stuffz to use alpha instead of an icon state

### ISSUE THREAD

**Issue by DuncanFairley** [DuncanFairley/TWC#214]
Make sure to delete the unused icon state.

**Comment by Rotem12** [comment]
I'm not so sure if it's wise to do this in the near future, maybe if and when my feature request is added or if I find a workaround
http://www.byond.com/forum/?post=1763451
http://www.byond.com/forum/?post=1763636

I still have no way of applying, color, alpha or transform to the icon without effecting the name tag. Using Alpha is less horrible than transform but it's still not optimal. While this may seem like a tiny cosmetic change, Justin set alpha to 36 which is pretty low and people with magic eyes may not see people who wear invisibility cloak since name tags won't be visible much either.

Another thing to test is how alpha reacts in hardware/software rendering mode as well all webclient render modes.

And last, if we do this change, it also means that preventing transfiguration while invisible is no longer a need and we can now allow it.
