### ISSUE TITLE
Give players the ability to remove themselves from Vault entry lists

### ISSUE THREAD

**Issue by Juxnist** [DuncanFairley/TWC#277]
Probably add some way to prevent randoms from doing it as well. Like some type of accept/decline thing when someone adds you to their vault allow list.

**Comment by Rotem12** [comment]
Why is this a problem? 

I don't see a real purpose in this. So you get a bunch of extra names in your enter list, if it's that uncomfortable just find an alternative way to vault visiting, I really don't see a reason to "decline".

**Comment by Juxnist** [comment]
Don't care if there is a decline thing. It was just an idea that came to me when I was writing it. I just hate the popup when you try to go into your vault. Them randoms giving me access.

**Comment by Rotem12** [comment]
If it's that uncomfortable just find an alternative way to vault visiting, there could be for example 2 entrances, one to enter other people's vault and one to enter yours.

I just want the best solution for the problem, feel free to make a suggestion in order to harvest the creativity of the entire TWC community.

**Comment by DuncanFairley** [comment]
If the person is in your PM block list, don't show them in the vault list.
