### ISSUE TITLE
Spell book issue (the one next to the PM Box)

### ISSUE THREAD

**Issue by LuckySara** [DuncanFairley/TWC#452]
Alexander reported to me, that the Spell book, when having it opened to show the 1 through =
If you drag and drop them, they'll be deleted. When you relog, they do not reappear. And once it is deleted, the macro does not work (Which I suspect that is supposed to happen)

I asked him to show me a screenshot: http://i.imgur.com/yODthFQ.png

When I asked him if he can get it re-opened to see the empty boxes again, but apparently he can not.

**Comment by Rotem12** [comment]
When a spell is dragged off actionbar when spell book is closed, the spell will disappear from actionbar and with it, the slot will go invisible.

When opening spellbook, all slots are once again visible and you can make a new macro. If you are referring to the intentional behavior then no, it is not a bug. 

I can not see any sort of buggy behavior with actionbar. If you are seeing an actual bug, please provide detailed step by step to reproduce it.
