### ISSUE TITLE
Multiple icon issues

### ISSUE THREAD

**Issue by Malificium** [DuncanFairley/TWC#481]
There appears to be a few image-related problems.

**Firstly:** A bug that resulted in some kind of distorted icon that moved across the screen. This icon appeared both when I was inside buildings and outside of them.

![twc bug](https://cloud.githubusercontent.com/assets/18757071/14939345/4509bebc-0f3a-11e6-8a21-8bc560cfd61f.png)

**Secondly:** A bug with my own personal icon. When I was moving 'north' my icon was morphed into the following image. It only occurred when moving in this direction, not any other direction.

![twc bug 2](https://cloud.githubusercontent.com/assets/18757071/14939360/297ffd72-0f3b-11e6-96c0-4338fff38a19.png)

**Finally:** An issue with the secret entrances. The 'book of chaos' appeared at the beginning of all the secret entrances within Hogwarts. This particular issue only appeared when the entrance was closed; when it was open the pathway would appear as it normally does.

![twc bug 3](https://cloud.githubusercontent.com/assets/18757071/14939362/3d809548-0f3b-11e6-90bb-1ec1b5ec66fc.png)

I have been informed that there was a report of some similar issues through more informal channels but wanted to ensure that you were aware.

**Comment by Rotem12** [comment]
All the above are a result of a beta BYOND build we're using, 2 separate issues I suspect.

I know that the problem in the last screen was fixed by adding an appearance flag to roof edges, this change exists for next update.

The other 2 are not related to TWC and I can't do anything to fix it, it's a BYOND issue and will hopefully be gone with a BYOND server upgrade, if you have the ability to force those issues on your end, I'd love to know exact steps so I could reproduce it on my end and see if it changes on newer BYOND versions. (Then post a BYOND bug report if not)
